# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69307237e1c574160afb8488a3c65b13f48c7350eb5128105cae9840c860eaf0b90ec8a01076d4ffb59a47c600f1ea783999d65996b4c9cb3a5be4833c348209

test:
  secret_key_base: 80d20c3f6e7b03ef34e605f6afd5eff01082a98f0142483216360b1e13d75f54ba299e744cbd8b87c521cf6a2c5c2687ad75d6cf4d8c0d53d53773d240054ab5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
